package rules.capter02

import com.cloudy.capter02.Person

rule "lock-on-active-01"
no-loop true
when
    $person: Person(age < 20)
then
    System.out.println("rule-flow-group-01");
    $person.setAge(18);
    update($person)
end

rule "lock-on-active-02"
dialect "mvel"
lock-on-active true
when
    $person: Person(age < 20)
then
    System.out.println("rule-flow-group-02");
    System.out.println("age:" + $person.age)
end

